### ISSUE TITLE
How does SSR function gets triggered?

### ISSUE THREAD

**Issue by lukaskoeller** [yarbsemaj/sveltekit-adapter-lambda#21]
First of all, neat stuff you created there! 🤩 

I am trying to implement it using Pulumi instead of serverless (still quite new to all of it).

I managed to upload prerendered and assets to s3, create a cloudfront distribution and connect it with the edge function. Working so far ✅ 

Now I wanted to deploy the SSR function (`build/server/serverless.handler`). I just wonder though, how and when this function gets triggered? I see you create an URL for it (`serverless.yml:51`), so I assume its called via an http request (?) but this url of course doesn't exist at build time of the svelte app. Your blog entry indicated an api gateway in between, though can't see you defining it in your `serverless.yml`.

Would you be so kind to point me into the right direction?

**Comment by yarbsemaj** [comment]
Hi @lukaskoeller, thank you for your interest in my project!

The blog post is a bit out of date, i'll get on updating that. Previously it did use an API gateway, but since Amazon added support for [Lambda function urls](https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/) this has no longer been necessary as thus to save cost I removed the API gateway.

When there was an API gateway, serverless took care of creating it for you, you just specify the event (in this case a http request), the path and the function you want to call and serverless did job of creating the api gateway, route, IAM roles etc.

As for how its called now, you are correct that it's just a http request, if you hit the function URL you will get back the HTML (or JSON etc..) of the page you are visiting. The path, query params and headers are proxied through by cloudfront onto that http call with logic inside the lambda extracting then and passing them to your sveltekit app. 
The function url of the SSR lambda is the default origin of the cloudfront with origin been changed by the edge function if the file is on the manifest of files in S3.

I hope that cleared everything up for you.

**Comment by lukaskoeller** [comment]
Many thanks @yarbsemaj, instant reply 😍 

I think I got it. By default cloudfronts origin is the lambda function url. But if the edge function detects a static asset it instead routes to the s3 origin?

_(Will try that later and share a code excerpt for people using pulumi too)_

**Comment by lukaskoeller** [comment]
A more generic question. Wouldn't it be possible to modify the build to separate ssr stuff and static stuff in a way that static assets follow a certain path pattern (e.g. always `static/**/*`) and use [path pattern](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesPathPattern) with two origins to route to the S3 (path includes `static`) or S3. Thus, getting rid of the Lambda@Edge?

**Comment by yarbsemaj** [comment]
You could, but then that would remove the option of having any static assets outside the static folder, (i.e, in the public folder) so things like favicons, or .well-known, it also would remove the option for serving pre-compiled pages from S3.

**Comment by lukaskoeller** [comment]
That's a good point, makes totally sense this way. Thanks for the explanation!

**Comment by lukaskoeller** [comment]
Okay I hope one last thing 😅 

I made everything working (thanks again). Though, one thing is different. I had to configure the `originProtocolPolicy` with `http-only`, instead of `https-only` how you did it.

Concerning that, I found the following in the [AWS Docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOAIRestrictBucketAccess):
> HTTP only is the default setting when the origin is an Amazon S3 static website hosting endpoint, because Amazon S3 doesn’t support HTTPS connections for static website hosting endpoints. The CloudFront console does not support changing this setting for Amazon S3 static website hosting endpoints.

With `https-only` I was constantly getting 502 Bad Gateway on all S3 Resources.

How do you make that work?

**Comment by yarbsemaj** [comment]
I'm not using static site hosting for my assets, I just rewrite the origin to the file in the bucket, and have bucket files public read.

**Comment by lukaskoeller** [comment]
Ok the problem is using dot notation (`.`) for the bucket name. AWS has wildcard SSL certificate for `*.s3.amazonaws.com` which doesn't apply for buckets with dot notation. Hence, s3 is served via http instead of https. Renaming the bucket using dash (`-`) worked just fine.
